const data = [
  {
    id: '5e9f5ee35eb9e72bc21af4a2',
    group: 0,
    page: 0,
    word: 'boat',
    image: 'files/01_0005.jpg',
    audio: 'files/01_0005.mp3',
    audioMeaning: 'files/01_0005_meaning.mp3',
    audioExample: 'files/01_0005_example.mp3',
    textMeaning: 'A <i>boat</i> is a vehicle that moves across water.',
    textExample: 'There is a small <b>boat</b> on the lake.',
    transcription: '[bout]',
    textExampleTranslate: 'На озере есть маленькая лодка',
    textMeaningTranslate: 'Лодка - это транспортное средство, которое движется по воде',
    wordTranslate: 'лодка',
    wordsPerExampleSentence: 8,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4a1',
    group: 0,
    page: 0,
    word: 'agree',
    image: 'files/01_0001.jpg',
    audio: 'files/01_0001.mp3',
    audioMeaning: 'files/01_0001_meaning.mp3',
    audioExample: 'files/01_0001_example.mp3',
    textMeaning: 'To <i>agree</i> is to have the same opinion or belief as another person.',
    textExample: 'The students <b>agree</b> they have too much homework.',
    transcription: '[əgríː]',
    textExampleTranslate: 'Студенты согласны, что у них слишком много домашней работы',
    textMeaningTranslate: 'Согласиться - значит иметь то же мнение или убеждение, что и другой человек',
    wordTranslate: 'согласна',
    wordsPerExampleSentence: 8,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4a3',
    group: 0,
    page: 0,
    word: 'arrive',
    image: 'files/01_0003.jpg',
    audio: 'files/01_0003.mp3',
    audioMeaning: 'files/01_0003_meaning.mp3',
    audioExample: 'files/01_0003_example.mp3',
    textMeaning: 'To <i>arrive</i> is to get somewhere.',
    textExample: 'They <b>arrived</b> at school at 7 a.m.',
    transcription: '[əráiv]',
    textExampleTranslate: 'Они прибыли в школу в 7 часов утра',
    textMeaningTranslate: 'Приехать значит попасть куда-то',
    wordTranslate: 'прибыть',
    wordsPerExampleSentence: 7,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4a4',
    group: 0,
    page: 0,
    word: 'August',
    image: 'files/01_0004.jpg',
    audio: 'files/01_0004.mp3',
    audioMeaning: 'files/01_0004_meaning.mp3',
    audioExample: 'files/01_0004_example.mp3',
    textMeaning: '<i>August</i> is the eighth month of the year.',
    textExample: 'Is your birthday in <b>August</b>?',
    transcription: '[ɔ́ːgəst]',
    textExampleTranslate: 'У тебя день рождения в августе?',
    textMeaningTranslate: 'Август - восьмой месяц года',
    wordTranslate: 'август',
    wordsPerExampleSentence: 5,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4a5',
    group: 0,
    page: 0,
    word: 'breakfast',
    image: 'files/01_0006.jpg',
    audio: 'files/01_0006.mp3',
    audioMeaning: 'files/01_0006_meaning.mp3',
    audioExample: 'files/01_0006_example.mp3',
    textMeaning: '<i>Breakfast</i> is the morning meal.',
    textExample: 'I ate eggs for <b>breakfast</b>.',
    transcription: '[brekfəst]',
    textExampleTranslate: 'Я ел яйца на завтрак',
    textMeaningTranslate: 'Завтрак - это утренняя трапеза',
    wordTranslate: 'завтрак',
    wordsPerExampleSentence: 5,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4a6',
    group: 0,
    page: 0,
    word: 'camera',
    image: 'files/01_0007.jpg',
    audio: 'files/01_0007.mp3',
    audioMeaning: 'files/01_0007_meaning.mp3',
    audioExample: 'files/01_0007_example.mp3',
    textMeaning: 'A <i>camera</i> is a piece of equipment that takes pictures.',
    textExample: 'I brought my <b>camera</b> on my vacation.',
    transcription: '[kǽmərə]',
    textExampleTranslate: 'Я принес свою камеру в отпуск',
    textMeaningTranslate: 'Камера - это часть оборудования, которая делает снимки',
    wordTranslate: 'камера',
    wordsPerExampleSentence: 7,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4a7',
    group: 0,
    page: 0,
    word: 'capital',
    image: 'files/01_0008.jpg',
    audio: 'files/01_0008.mp3',
    audioMeaning: 'files/01_0008_meaning.mp3',
    audioExample: 'files/01_0008_example.mp3',
    textMeaning: 'A <i>capital</i> is a city where a country’s government is based.',
    textExample: 'The <b>capital</b> of the United States is Washington, D.C.',
    transcription: '[kæpətl]',
    textExampleTranslate: 'Столица Соединенных Штатов - Вашингтон, округ Колумбия',
    textMeaningTranslate: 'Столица - это город, в котором базируется правительство страны',
    wordTranslate: 'столица',
    wordsPerExampleSentence: 9,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4a8',
    group: 0,
    page: 0,
    word: 'catch',
    image: 'files/01_0009.jpg',
    audio: 'files/01_0009.mp3',
    audioMeaning: 'files/01_0009_meaning.mp3',
    audioExample: 'files/01_0009_example.mp3',
    textMeaning: 'To <i>catch</i> is to grab or get something.',
    textExample: 'Did you <b>catch</b> the ball during the baseball game?',
    transcription: '[kætʃ]',
    textExampleTranslate: 'Вы поймали мяч во время игры в бейсбол?',
    textMeaningTranslate: 'Поймать - значит схватить или получить что-то',
    wordTranslate: 'поймать',
    wordsPerExampleSentence: 9,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4a9',
    group: 0,
    page: 0,
    word: 'duck',
    image: 'files/01_0010.jpg',
    audio: 'files/01_0010.mp3',
    audioMeaning: 'files/01_0010_meaning.mp3',
    audioExample: 'files/01_0010_example.mp3',
    textMeaning: 'A <i>duck</i> is a small water bird.',
    textExample: 'People feed <b>ducks</b> at the lake.',
    transcription: '[dʌk]',
    textExampleTranslate: 'Люди кормят уток у озера',
    textMeaningTranslate: 'Утка - маленькая водяная птица',
    wordTranslate: 'утка',
    wordsPerExampleSentence: 6,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4aa',
    group: 0,
    page: 0,
    word: 'enjoy',
    image: 'files/01_0011.jpg',
    audio: 'files/01_0011.mp3',
    audioMeaning: 'files/01_0011_meaning.mp3',
    audioExample: 'files/01_0011_example.mp3',
    textMeaning: 'To <i>enjoy</i> is to like something.',
    textExample: 'The woman <b>enjoys</b> riding her bicycle.',
    transcription: '[indʒɔ́i]',
    textExampleTranslate: 'Женщина любит кататься на велосипеде',
    textMeaningTranslate: 'Наслаждаться значит любить что-то',
    wordTranslate: 'наслаждаться',
    wordsPerExampleSentence: 6,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4ab',
    group: 0,
    page: 0,
    word: 'invite',
    image: 'files/01_0012.jpg',
    audio: 'files/01_0012.mp3',
    audioMeaning: 'files/01_0012_meaning.mp3',
    audioExample: 'files/01_0012_example.mp3',
    textMeaning: 'To <i>invite</i> is to ask someone to come to a place or event.',
    textExample: 'I will <b>invite</b> my friends to my birthday party.',
    transcription: '[inváit]',
    textExampleTranslate: 'Я приглашаю своих друзей на мой день рождения',
    textMeaningTranslate: 'Пригласить - это попросить кого-нибудь прийти на место или событие',
    wordTranslate: 'пригласить',
    wordsPerExampleSentence: 9,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4ac',
    group: 0,
    page: 0,
    word: 'month',
    image: 'files/01_0014.jpg',
    audio: 'files/01_0014.mp3',
    audioMeaning: 'files/01_0014_meaning.mp3',
    audioExample: 'files/01_0014_example.mp3',
    textMeaning: 'A <i>month</i> is one of 12 periods of time in one year.',
    textExample: 'January is the first <b>month</b> of the year.',
    transcription: '[mʌnθ]',
    textExampleTranslate: 'январь - первый месяц года',
    textMeaningTranslate: 'Месяц - это один из 12 периодов времени в году',
    wordTranslate: 'месяц',
    wordsPerExampleSentence: 8,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4ad',
    group: 0,
    page: 0,
    word: 'travel',
    image: 'files/01_0015.jpg',
    audio: 'files/01_0015.mp3',
    audioMeaning: 'files/01_0015_meaning.mp3',
    audioExample: 'files/01_0015_example.mp3',
    textMeaning: 'To <i>travel</i> is to go to a faraway place on vacation or business.',
    textExample: 'They will <b>travel</b> to Argentina this summer.',
    transcription: '[trǽvəl]',
    textExampleTranslate: 'Этим летом они отправятся в Аргентину',
    textMeaningTranslate: 'Путешествовать - это отправиться в далекое место на отдых или по делам',
    wordTranslate: 'путешествовать',
    wordsPerExampleSentence: 7,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4ae',
    group: 0,
    page: 0,
    word: 'love',
    image: 'files/01_0013.jpg',
    audio: 'files/01_0013.mp3',
    audioMeaning: 'files/01_0013_meaning.mp3',
    audioExample: 'files/01_0013_example.mp3',
    textMeaning: 'To <i>love</i> is to like something or someone a lot.',
    textExample: 'I <b>love</b> my family very much.',
    transcription: '[lʌv]',
    textExampleTranslate: 'Я очень люблю свою семью',
    textMeaningTranslate: 'Любить значит любить что-то или кого-то много',
    wordTranslate: 'любовь',
    wordsPerExampleSentence: 6,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4af',
    group: 0,
    page: 0,
    word: 'typical',
    image: 'files/01_0016.jpg',
    audio: 'files/01_0016.mp3',
    audioMeaning: 'files/01_0016_meaning.mp3',
    audioExample: 'files/01_0016_example.mp3',
    textMeaning: 'If something is <i>typical</i>, it is normal, or something that usually happens.',
    textExample: 'My <b>typical</b> breakfast is toast and eggs.',
    transcription: '[típikəl]',
    textExampleTranslate: 'Мой типичный завтрак - тост и яйца',
    textMeaningTranslate: 'Если что-то типичное, это нормально, или что-то, что обычно происходит',
    wordTranslate: 'типичный',
    wordsPerExampleSentence: 7,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4b0',
    group: 0,
    page: 0,
    word: 'visit',
    image: 'files/01_0017.jpg',
    audio: 'files/01_0017.mp3',
    audioMeaning: 'files/01_0017_meaning.mp3',
    audioExample: 'files/01_0017_example.mp3',
    textMeaning: 'To <i>visit</i> is to go and spend time in another place or see another person.',
    textExample: 'She wants to <b>visit</b> her grandmother.',
    transcription: '[vízit]',
    textExampleTranslate: 'Она хочет навестить свою бабушку',
    textMeaningTranslate: 'Посетить - значит пойти и провести время в другом месте или увидеть другого человека',
    wordTranslate: 'посещение',
    wordsPerExampleSentence: 6,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4b1',
    group: 0,
    page: 0,
    word: 'weather',
    image: 'files/01_0018.jpg',
    audio: 'files/01_0018.mp3',
    audioMeaning: 'files/01_0018_meaning.mp3',
    audioExample: 'files/01_0018_example.mp3',
    textMeaning: '<i>Weather</i> is the temperature and the state of the outdoors.',
    textExample: 'Today’s <b>weather</b> is rainy and cloudy.',
    transcription: '[weðər]',
    textExampleTranslate: 'Сегодня погода дождливая и облачная',
    textMeaningTranslate: 'Погода это температура и состояние на улице',
    wordTranslate: 'погода',
    wordsPerExampleSentence: 6,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4b2',
    group: 0,
    page: 0,
    word: 'wine',
    image: 'files/01_0020.jpg',
    audio: 'files/01_0020.mp3',
    audioMeaning: 'files/01_0020_meaning.mp3',
    audioExample: 'files/01_0020_example.mp3',
    textMeaning: '<i>Wine</i> is an alcoholic drink made from grapes.',
    textExample: 'The store carried both red and white <b>wine</b>.',
    transcription: '[wain]',
    textExampleTranslate: 'В магазине было красное и белое вино',
    textMeaningTranslate: 'Вино - это алкогольный напиток из винограда',
    wordTranslate: 'вино',
    wordsPerExampleSentence: 8,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4b4',
    group: 0,
    page: 1,
    word: 'adventure',
    image: 'files/02_0021.jpg',
    audio: 'files/02_0021.mp3',
    audioMeaning: 'files/02_0021_meaning.mp3',
    audioExample: 'files/02_0021_example.mp3',
    textMeaning: 'An <i>adventure</i> is a fun or exciting thing that you do.',
    textExample: 'Riding in the rough water was an <b>adventure</b>.',
    transcription: '[ədvéntʃər]',
    textExampleTranslate: 'Езда в бурной воде была приключением',
    textMeaningTranslate: 'Приключение - это забавная или захватывающая вещь, которую ты делаешь',
    wordTranslate: 'приключение',
    wordsPerExampleSentence: 8,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4b3',
    group: 0,
    page: 0,
    word: 'week',
    image: 'files/01_0019.jpg',
    audio: 'files/01_0019.mp3',
    audioMeaning: 'files/01_0019_meaning.mp3',
    audioExample: 'files/01_0019_example.mp3',
    textMeaning: 'A <i>week</i> is a period of time that is seven days long.',
    textExample: 'What are you doing next <b>week</b>?',
    transcription: '[wiːk]',
    textExampleTranslate: 'Что ты делаешь на следующей неделе?',
    textMeaningTranslate: 'Неделя - это период времени, который длится семь дней',
    wordTranslate: 'неделя',
    wordsPerExampleSentence: 6,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4b5',
    group: 0,
    page: 1,
    word: 'approach',
    image: 'files/02_0022.jpg',
    audio: 'files/02_0022.mp3',
    audioMeaning: 'files/02_0022_meaning.mp3',
    audioExample: 'files/02_0022_example.mp3',
    textMeaning: 'To <i>approach</i> something means to move close to it.',
    textExample: 'The boy <b>approached</b> his school.',
    transcription: '[əpróutʃ]',
    textExampleTranslate: 'Мальчик приблизился к своей школе',
    textMeaningTranslate: 'Подойти к чему-то - значит приблизиться к нему',
    wordTranslate: 'подходить',
    wordsPerExampleSentence: 5,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4b6',
    group: 0,
    page: 1,
    word: 'chemical',
    image: 'files/02_0024.jpg',
    audio: 'files/02_0024.mp3',
    audioMeaning: 'files/02_0024_meaning.mp3',
    audioExample: 'files/02_0024_example.mp3',
    textMeaning: 'A <i>chemical</i> is something that scientists use in chemistry.',
    textExample: 'The scientist mixed the <b>chemicals</b>.',
    transcription: '[kémikəl]',
    textExampleTranslate: 'Ученый смешал химикаты',
    textMeaningTranslate: 'Химическое вещество - это то, что ученые используют в химии',
    wordTranslate: 'химический',
    wordsPerExampleSentence: 5,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4b7',
    group: 0,
    page: 1,
    word: 'carefully',
    image: 'files/02_0023.jpg',
    audio: 'files/02_0023.mp3',
    audioMeaning: 'files/02_0023_meaning.mp3',
    audioExample: 'files/02_0023_example.mp3',
    textMeaning: '<i>Carefully</i> means with great attention, especially to detail or safety.',
    textExample: 'The baby <b>carefully</b> climbed down the stairs.',
    transcription: '[kɛ́ərfəli]',
    textExampleTranslate: 'Малыш осторожно спускался по лестнице',
    textMeaningTranslate: 'Осторожно означает с большим вниманием, особенно к деталям или безопасности',
    wordTranslate: 'внимательно',
    wordsPerExampleSentence: 7,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4b8',
    group: 0,
    page: 1,
    word: 'create',
    image: 'files/02_0025.jpg',
    audio: 'files/02_0025.mp3',
    audioMeaning: 'files/02_0025_meaning.mp3',
    audioExample: 'files/02_0025_example.mp3',
    textMeaning: 'To <i>create</i> means to make something new.',
    textExample: 'She <b>created</b> an igloo from blocks of snow.',
    transcription: '[kriéit]',
    textExampleTranslate: 'Она создала иглу из снежных глыб',
    textMeaningTranslate: 'Создать значит создать что-то новое',
    wordTranslate: 'создайте',
    wordsPerExampleSentence: 8,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4ba',
    group: 0,
    page: 1,
    word: 'experiment',
    image: 'files/02_0027.jpg',
    audio: 'files/02_0027.mp3',
    audioMeaning: 'files/02_0027_meaning.mp3',
    audioExample: 'files/02_0027_example.mp3',
    textMeaning: 'An <i>experiment</i> is a test that you do to see what will happen.',
    textExample: 'The student did an <b>experiment</b> in science class.',
    transcription: '[ikspérəmənt]',
    textExampleTranslate: 'Студент сделал эксперимент в классе науки',
    textMeaningTranslate: 'Эксперимент - это тест, который вы проводите, чтобы увидеть, что произойдет',
    wordTranslate: 'эксперимент',
    wordsPerExampleSentence: 8,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4bb',
    group: 0,
    page: 1,
    word: 'laboratory',
    image: 'files/02_0029.jpg',
    audio: 'files/02_0029.mp3',
    audioMeaning: 'files/02_0029_meaning.mp3',
    audioExample: 'files/02_0029_example.mp3',
    textMeaning: 'A <i>laboratory</i> is a room where a scientist works.',
    textExample: 'My mother works in a <b>laboratory</b>.',
    transcription: '[lǽbərətɔ̀ːri]',
    textExampleTranslate: 'Моя мама работает в лаборатории',
    textMeaningTranslate: 'Лаборатория - это комната, где работает ученый',
    wordTranslate: 'лаборатория',
    wordsPerExampleSentence: 6,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4bc',
    group: 0,
    page: 1,
    word: 'kill',
    image: 'files/02_0028.jpg',
    audio: 'files/02_0028.mp3',
    audioMeaning: 'files/02_0028_meaning.mp3',
    audioExample: 'files/02_0028_example.mp3',
    textMeaning: 'To <i>kill</i> someone or something is to make them die.',
    textExample: 'I <b>killed</b> the fly.',
    transcription: '[kil]',
    textExampleTranslate: 'Я убил муху',
    textMeaningTranslate: 'Убить кого-то или что-то значит заставить их умереть',
    wordTranslate: 'убийство',
    wordsPerExampleSentence: 4,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4bd',
    group: 0,
    page: 1,
    word: 'laugh',
    image: 'files/02_0030.jpg',
    audio: 'files/02_0030.mp3',
    audioMeaning: 'files/02_0030_meaning.mp3',
    audioExample: 'files/02_0030_example.mp3',
    textMeaning: '<i>Laugh</i> is the sound made when someone is happy or a funny thing occurs.',
    textExample: 'The sound of her <b>laugh</b> filled the room.',
    transcription: '[læf]',
    textExampleTranslate: 'Звук ее смеха заполнил комнату',
    textMeaningTranslate: 'Смех - это звук, который звучит, когда кто-то счастлив или происходит смешная вещь',
    wordTranslate: 'смех',
    wordsPerExampleSentence: 8,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4bf',
    group: 0,
    page: 1,
    word: 'nervous',
    image: 'files/02_0032.jpg',
    audio: 'files/02_0032.mp3',
    audioMeaning: 'files/02_0032_meaning.mp3',
    audioExample: 'files/02_0032_example.mp3',
    textMeaning: 'When a person is <i>nervous</i>, they think something bad will happen.',
    textExample: 'The boy became <b>nervous</b> when he heard the news.',
    transcription: '[nə́ːrvəs]',
    textExampleTranslate: 'Мальчик стал нервным, когда услышал новости',
    textMeaningTranslate: 'Когда человек нервничает, он думает, что случится что-то плохое',
    wordTranslate: 'нервная',
    wordsPerExampleSentence: 9,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4c0',
    group: 0,
    page: 1,
    word: 'noise',
    image: 'files/02_0033.jpg',
    audio: 'files/02_0033.mp3',
    audioMeaning: 'files/02_0033_meaning.mp3',
    audioExample: 'files/02_0033_example.mp3',
    textMeaning: 'A <i>noise</i> is an unpleasant sound.',
    textExample: 'The crying baby made a loud <b>noise</b>.',
    transcription: '[nɔiz]',
    textExampleTranslate: 'Плачущий ребенок издал громкий шум',
    textMeaningTranslate: 'Шум - это неприятный звук',
    wordTranslate: 'шум',
    wordsPerExampleSentence: 7,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4c2',
    group: 0,
    page: 1,
    word: 'project',
    image: 'files/02_0034.jpg',
    audio: 'files/02_0034.mp3',
    audioMeaning: 'files/02_0034_meaning.mp3',
    audioExample: 'files/02_0034_example.mp3',
    textMeaning: 'A <i>project</i> is a type of work that you do for school or a job.',
    textExample: 'His afternoon work <b>project</b> was to paint the room green.',
    transcription: '[prάdʒekt]',
    textExampleTranslate: 'Его дневной рабочий проект должен был покрасить комнату в зеленый цвет',
    textMeaningTranslate: 'Проект - это вид работы, которую вы делаете для школы или работы',
    wordTranslate: 'проект',
    wordsPerExampleSentence: 10,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4c3',
    group: 0,
    page: 1,
    word: 'secret',
    image: 'files/02_0036.jpg',
    audio: 'files/02_0036.mp3',
    audioMeaning: 'files/02_0036_meaning.mp3',
    audioExample: 'files/02_0036_example.mp3',
    textMeaning: 'A <i>secret</i> is something that you do not tell other people.',
    textExample: 'The two boys were sharing a <b>secret</b>.',
    transcription: '[síːkrit]',
    textExampleTranslate: 'Два мальчика делились секретом',
    textMeaningTranslate: 'Секрет это то, что вы не говорите другим людям',
    wordTranslate: 'секрет',
    wordsPerExampleSentence: 7,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4c5',
    group: 0,
    page: 1,
    word: 'smell',
    image: 'files/02_0038.jpg',
    audio: 'files/02_0038.mp3',
    audioMeaning: 'files/02_0038_meaning.mp3',
    audioExample: 'files/02_0038_example.mp3',
    textMeaning: 'To <i>smell</i> something means to use your nose to sense it.',
    textExample: 'The two friends <b>smelled</b> the flower.',
    transcription: '[smel]',
    textExampleTranslate: 'Два друга понюхали цветок',
    textMeaningTranslate: 'Обонять что-то значит использовать свой нос, чтобы почувствовать это',
    wordTranslate: 'запах',
    wordsPerExampleSentence: 6,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4c6',
    group: 0,
    page: 1,
    word: 'terrible',
    image: 'files/02_0039.jpg',
    audio: 'files/02_0039.mp3',
    audioMeaning: 'files/02_0039_meaning.mp3',
    audioExample: 'files/02_0039_example.mp3',
    textMeaning: 'If something is <i>terrible</i>, it is very bad.',
    textExample: 'The way he treated his classmate was <b>terrible</b>.',
    transcription: '[térəbəl]',
    textExampleTranslate: 'То, как он относился к своему однокласснику, было ужасно',
    textMeaningTranslate: 'Если что-то ужасно, это очень плохо',
    wordTranslate: 'ужасный',
    wordsPerExampleSentence: 8,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4c7',
    group: 0,
    page: 1,
    word: 'worse',
    image: 'files/02_0040.jpg',
    audio: 'files/02_0040.mp3',
    audioMeaning: 'files/02_0040_meaning.mp3',
    audioExample: 'files/02_0040_example.mp3',
    textMeaning: 'If something is <i>worse</i>, it is of poorer quality than another thing.',
    textExample: 'Business was <b>worse</b> this month than last month.',
    transcription: '[wəːrs]',
    textExampleTranslate: 'Бизнес был хуже в этом месяце, чем в прошлом месяце',
    textMeaningTranslate: 'Если что-то хуже, это хуже, чем что-то другое',
    wordTranslate: 'хуже',
    wordsPerExampleSentence: 8,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4c8',
    group: 0,
    page: 2,
    word: 'alien',
    image: 'files/03_0041.jpg',
    audio: 'files/03_0041.mp3',
    audioMeaning: 'files/03_0041_meaning.mp3',
    audioExample: 'files/03_0041_example.mp3',
    textMeaning: 'An <i>alien</i> is a creature from a different world.',
    textExample: 'The <b>alien</b> came in peace.',
    transcription: '[éiljən]',
    textExampleTranslate: 'пришелец пришел с миром',
    textMeaningTranslate: 'Инопланетянин - это существо из другого мира',
    wordTranslate: 'инопланетянин',
    wordsPerExampleSentence: 5,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4c9',
    group: 0,
    page: 2,
    word: 'among',
    image: 'files/03_0042.jpg',
    audio: 'files/03_0042.mp3',
    audioMeaning: 'files/03_0042_meaning.mp3',
    audioExample: 'files/03_0042_example.mp3',
    textMeaning: 'If you are <i>among</i> certain things, they are all around you.',
    textExample: 'There was a red apple <b>among</b> the green ones.',
    transcription: '[əmʌ̀ŋ]',
    textExampleTranslate: 'Среди зеленых было красное яблоко',
    textMeaningTranslate: 'Если вы среди определенных вещей, они все вокруг вас',
    wordTranslate: 'среди',
    wordsPerExampleSentence: 9,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4ca',
    group: 0,
    page: 2,
    word: 'chart',
    image: 'files/03_0043.jpg',
    audio: 'files/03_0043.mp3',
    audioMeaning: 'files/03_0043_meaning.mp3',
    audioExample: 'files/03_0043_example.mp3',
    textMeaning: 'A <i>chart</i> is a list of information.',
    textExample: 'We used a <b>chart</b> to see how we had improved.',
    transcription: '[tʃɑːrt]',
    textExampleTranslate: 'Мы использовали график, чтобы увидеть, как мы улучшили',
    textMeaningTranslate: 'Диаграмма - это список информации',
    wordTranslate: 'диаграмма',
    wordsPerExampleSentence: 10,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4cb',
    group: 0,
    page: 2,
    word: 'cloud',
    image: 'files/03_0044.jpg',
    audio: 'files/03_0044.mp3',
    audioMeaning: 'files/03_0044_meaning.mp3',
    audioExample: 'files/03_0044_example.mp3',
    textMeaning: 'A <i>cloud</i> is a group of water drops in the sky.',
    textExample: 'The sky was filled with white <b>clouds</b>.',
    transcription: '[klaud]',
    textExampleTranslate: 'Небо было наполнено белыми облаками',
    textMeaningTranslate: 'Облако - это группа капель воды в небе',
    wordTranslate: 'облако',
    wordsPerExampleSentence: 7,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4ce',
    group: 0,
    page: 2,
    word: 'fail',
    image: 'files/03_0047.jpg',
    audio: 'files/03_0047.mp3',
    audioMeaning: 'files/03_0047_meaning.mp3',
    audioExample: 'files/03_0047_example.mp3',
    textMeaning: 'To <i>fail</i> means you do not succeed in what you try to do.',
    textExample: 'Since he <b>failed</b> to get the job, he was sad.',
    transcription: '[feil]',
    textExampleTranslate: 'Так как он не смог получить работу, ему было грустно',
    textMeaningTranslate: 'Неудача означает, что вам не удается то, что вы пытаетесь сделать',
    wordTranslate: 'потерпеть поражение',
    wordsPerExampleSentence: 10,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4cf',
    group: 0,
    page: 2,
    word: 'grade',
    image: 'files/03_0048.jpg',
    audio: 'files/03_0048.mp3',
    audioMeaning: 'files/03_0048_meaning.mp3',
    audioExample: 'files/03_0048_example.mp3',
    textMeaning: 'A <i>grade</i> is a score or mark given to someone’s work.',
    textExample: 'I managed to get good <b>grades</b> on my report card.',
    transcription: '[greid]',
    textExampleTranslate: 'Мне удалось получить хорошие оценки на моем табеле',
    textMeaningTranslate: 'Оценка - это оценка или оценка, присвоенная чьей-либо работе',
    wordTranslate: 'класс',
    wordsPerExampleSentence: 10,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4d0',
    group: 0,
    page: 2,
    word: 'instead',
    image: 'files/03_0049.jpg',
    audio: 'files/03_0049.mp3',
    audioMeaning: 'files/03_0049_meaning.mp3',
    audioExample: 'files/03_0049_example.mp3',
    textMeaning: '<i>Instead</i> means in place of.',
    textExample: 'He ate the carrot <b>instead</b> of the ice cream.',
    transcription: '[instéd]',
    textExampleTranslate: 'Он съел морковку вместо мороженого',
    textMeaningTranslate: 'Вместо означает вместо',
    wordTranslate: 'вместо',
    wordsPerExampleSentence: 9,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4d1',
    group: 0,
    page: 2,
    word: 'library',
    image: 'files/03_0050.jpg',
    audio: 'files/03_0050.mp3',
    audioMeaning: 'files/03_0050_meaning.mp3',
    audioExample: 'files/03_0050_example.mp3',
    textMeaning: 'A <i>library</i> is a place where you go to read books.',
    textExample: 'The <b>library</b> at school is full of books.',
    transcription: '[láibrèri]',
    textExampleTranslate: 'Библиотека в школе полна книг',
    textMeaningTranslate: 'Библиотека - это место, куда вы ходите читать книги',
    wordTranslate: 'библиотека',
    wordsPerExampleSentence: 8,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4d2',
    group: 0,
    page: 2,
    word: 'photograph',
    image: 'files/03_0051.jpg',
    audio: 'files/03_0051.mp3',
    audioMeaning: 'files/03_0051_meaning.mp3',
    audioExample: 'files/03_0051_example.mp3',
    textMeaning: 'I like taking <i>photographs</i>.',
    textExample: 'I took this <b>photograph</b> with my cell phone.',
    transcription: '[fóutəgrӕf]',
    textExampleTranslate: 'Я сделал эту фотографию на свой мобильный',
    textMeaningTranslate: 'Мне нравится фотографировать',
    wordTranslate: 'фотография',
    wordsPerExampleSentence: 8,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4d3',
    group: 0,
    page: 2,
    word: 'planet',
    image: 'files/03_0052.jpg',
    audio: 'files/03_0052.mp3',
    audioMeaning: 'files/03_0052_meaning.mp3',
    audioExample: 'files/03_0052_example.mp3',
    textMeaning: 'A <i>planet</i> is a large round thing in space.',
    textExample: 'Saturn is the <b>planet</b> with the ring around it.',
    transcription: '[plǽnət]',
    textExampleTranslate: 'Сатурн - планета с кольцом вокруг него',
    textMeaningTranslate: 'Планета - это большая круглая вещь в космосе',
    wordTranslate: 'планета',
    wordsPerExampleSentence: 9,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4d4',
    group: 0,
    page: 2,
    word: 'report',
    image: 'files/03_0053.jpg',
    audio: 'files/03_0053.mp3',
    audioMeaning: 'files/03_0053_meaning.mp3',
    audioExample: 'files/03_0053_example.mp3',
    textMeaning: 'A <i>report</i> is something someone writes for school or work.',
    textExample: 'Karen had trouble writing her <b>report</b>.',
    transcription: '[ripɔ́ːrt]',
    textExampleTranslate: 'Карен не могла написать свой отчет',
    textMeaningTranslate: 'Отчет - это то, что кто-то пишет для школы или работы',
    wordTranslate: 'отчет',
    wordsPerExampleSentence: 6,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4d5',
    group: 0,
    page: 2,
    word: 'several',
    image: 'files/03_0054.jpg',
    audio: 'files/03_0054.mp3',
    audioMeaning: 'files/03_0054_meaning.mp3',
    audioExample: 'files/03_0054_example.mp3',
    textMeaning: '<i>Several</i> is more than two but not many.',
    textExample: 'He had to read <b>several</b> books for class.',
    transcription: '[sévərəl]',
    textExampleTranslate: 'Он должен был прочитать несколько книг для класса',
    textMeaningTranslate: 'Несколько больше двух, но не много',
    wordTranslate: 'несколько',
    wordsPerExampleSentence: 8,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4d7',
    group: 0,
    page: 2,
    word: 'solve',
    image: 'files/03_0056.jpg',
    audio: 'files/03_0056.mp3',
    audioMeaning: 'files/03_0056_meaning.mp3',
    audioExample: 'files/03_0056_example.mp3',
    textMeaning: 'To <i>solve</i> something is to find an answer to it.',
    textExample: 'All the students could easily <b>solve</b> the math problem.',
    transcription: '[sɑlv]',
    textExampleTranslate: 'Все ученики могли легко решить математическую задачу',
    textMeaningTranslate: 'Решить что-то - значит найти ответ',
    wordTranslate: 'решать',
    wordsPerExampleSentence: 9,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4d8',
    group: 0,
    page: 2,
    word: 'suddenly',
    image: 'files/03_0057.jpg',
    audio: 'files/03_0057.mp3',
    audioMeaning: 'files/03_0057_meaning.mp3',
    audioExample: 'files/03_0057_example.mp3',
    textMeaning: 'If something happens <i>suddenly</i>, it happens quickly and unexpectedly.',
    textExample: 'I was surprised when my friends <b>suddenly</b> shouted, “Happy birthday!”',
    transcription: '[sʌ́dnli]',
    textExampleTranslate: "Я был удивлен, когда мои друзья вдруг закричали: 'С днем рождения!'",
    textMeaningTranslate: 'Если что-то происходит внезапно, это происходит быстро и неожиданно',
    wordTranslate: 'вдруг, внезапно',
    wordsPerExampleSentence: 10,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4d9',
    group: 0,
    page: 2,
    word: 'suppose',
    image: 'files/03_0058.jpg',
    audio: 'files/03_0058.mp3',
    audioMeaning: 'files/03_0058_meaning.mp3',
    audioExample: 'files/03_0058_example.mp3',
    textMeaning: 'To <i>suppose</i> is to guess.',
    textExample: 'I <b>suppose</b> I should go home now.',
    transcription: '[səpóuz]',
    textExampleTranslate: 'Полагаю, мне пора домой',
    textMeaningTranslate: 'Предположить, значит угадать',
    wordTranslate: 'предположим',
    wordsPerExampleSentence: 7,
  },
];

export default data;
